query LihatSemuaUser @auth(level: PUBLIC) {
  profiles {
    id
    email
    namaLengkap
    role
  }
}

mutation addNewUser($id: String!, $email: String!, $namaLengkap: String!) @auth(level: PUBLIC) {
  profile_insert(data: {
    id: $id,
    email: $email,
    namaLengkap: $namaLengkap
  })
}

mutation addFormPengaduan(
  $id: String!,
  $namaLengkap: String!,
  $description: String!,
  $lokasi: String!,
  $pictureUrl: String
) @auth(level: PUBLIC) {
  pengaduan_insert(data: {
    id: $id,
    namaLengkap: $namaLengkap,
    description: $description,
    lokasi: $lokasi,
    pictureURl: $pictureUrl
  })
}